config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :authors
  resources :books
  resources :categories
  resources :libraries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :category
  belongs_to :library
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/library.rb
class Library < ApplicationRecord
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.all
  end

  def show
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(params_author)
    if @author.save
      redirect_to @author
    else
    render :new
    end
  end

  def edit
  end

  def update
    if @author.update(params_author)
      redirect_to author_path(@author.id)
    else
    render :edit
    end
  end

  def destroy
  @author.destroy
  redirect_to authors_path
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def params_author
    params.require(:author).permit(:first_name, :last_name)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
    @authors = Author.all
    @categories = Category.all
    @libraries = Library.all
  end

  def create
    @book = Book.new(params_book)
    if @book.save
      redirect_to @book
    else
      render :new
    end
  end

  def edit
    @authors = Author.all
    @categories = Category.all
    @libraries = Library.all
  end

  def update
    if @book.update(params_book)
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def params_book
    params.require(:book).permit(:parution_date, :title, :library_id, :category_id, :author_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params_category)
    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(params_category)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def params_category
    params.require(:category).permit(:name)
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
   before_action :set_library, only: [:show, :edit, :update, :destroy]

  def index
    @libraries = Library.all
  end

  def show
  end

  def new
    @library = Library.new
  end

  def create
    @library = Library.new(params_library)
    if @library.save
      redirect_to @library
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @library.update(params_library)
      redirect_to @library
    else
      render :edit
    end
  end

  def destroy
    @library.destroy
    redirect_to libraries_path
  end

  private

  def set_library
    @library = Library.find(params[:id])
  end

  def params_library
    params.require(:library).permit(:name, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/edit.html.erb
<%= simple_form_for @author do |f| %>
  <%=f.input :first_name %>
  <%=f.input :last_name %>
  <%=f.submit%>
<% end %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<%= link_to "Add Authors", new_author_path, class: "btn btn-info"%>
<% @authors.find_each do |author| %>
  <%= link_to author do %>
  <h2><%= author.first_name %> - <%= author.last_name %></h2>
  <% end %>
<% end %>

app/views/authors/new.html.erb
<%= simple_form_for @author do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.submit %>
<% end %>

app/views/authors/show.html.erb
<h1><%= @author.first_name %> - <%= @author.last_name %></h1>
<%= link_to 'Authors', authors_path, class: 'btn btn-info' %>
<%= link_to 'Update', edit_author_path(@author.id), class: 'btn btn-success' %>

app/views/books/edit.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.input :parution_date, as: :date, html5: true %>
  <%= f.input :library_id, :collection => @libraries, :label_method => :name, :value_method => :id, :label => "Library" ,:include_blank => false %>
  <%= f.input :category_id, :collection => @categories, :label_method => :name, :value_method => :id, :label => "Category" ,:include_blank => false %>
  <%= f.input :author_id, :collection => @authors, :label_method => :first_name, :value_method => :id, :label => "Author" ,:include_blank => false %>
  <%= f.submit %>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>

<%= link_to 'Add book', new_book_path, class: 'btn  btn-info' %>
<% @books.find_each do |book| %>
  <%= link_to book do %>
  <h2><%= book.title %></h2>
  <% end %>
<% end %>

app/views/books/new.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.input :parution_date, as: :date, html5: true %>
  <%= f.input :library_id, :collection => @libraries, :label_method => :name, :value_method => :id, :label => "Library" ,:include_blank => false %>
  <%= f.input :category_id, :collection => @categories, :label_method => :name, :value_method => :id, :label => "Category" ,:include_blank => false %>
  <%= f.input :author_id, :collection => @authors, :label_method => :first_name, :value_method => :id, :label => "Author" ,:include_blank => false %>
  <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %> - <%= @book.parution_date %> - <%= @book.author.last_name %> - <%= @book.category.name %> - <%= @book.library.name %></h1>
<%= link_to 'Books', books_path, class: 'btn btn-info' %>
<%= link_to 'Update', edit_book_path(@book.id), class: 'btn btn-success' %>

app/views/categories/edit.html.erb
<%= simple_form_for @categories do |f| %>
  <%= f.input :name  %>
  <%= f.submit  %>
<% end %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<%= link_to 'Add category', new_category_path, class: 'btn  btn-info' %>
<% @categories.find_each do |category| %>
  <%= link_to category do %>
  <h2><%= category.name %></h2>
  <% end %>
<% end %>

app/views/categories/new.html.erb
<%= simple_form_for @category do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/categories/show.html.erb
<%= @category.name %></h1>
<%= link_to 'Categories', categories_path, class: 'btn btn-info' %>
<%= link_to 'Update', edit_category_path(@category.id), class: 'btn btn-success' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainBookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/libraries/edit.html.erb
<%= simple_form_for @library do |f| %>
  <%= f.input :name %>
  <%= f.input :address  %>
  <%= f.submit  %>
<% end %>

app/views/libraries/index.html.erb
<h1>Librairies</h1>

<%= link_to 'Add library', new_library_path, class: 'btn  btn-info' %>
<% @libraries.find_each do |library| %>
  <%= link_to library do %>
  <h2><%= library.name %></h2>
  <% end %>
<% end %>

app/views/libraries/new.html.erb
<%= simple_form_for @library do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.submit %>
<% end %>

app/views/libraries/show.html.erb
<%= @library.name %></h1>
<%= link_to 'libraries', libraries_path, class: 'btn btn-info' %>
<%= link_to 'Update', edit_library_path(@library.id), class: 'btn btn-success' %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to 'Authors', authors_path, class: 'btn btn-primary' %>
<%= link_to 'Categories', categories_path, class: 'btn btn-primary' %>
<%= link_to 'Libraries', libraries_path, class: 'btn btn-primary' %>
<%= link_to 'Books', books_path, class: 'btn btn-primary' %>